### ISSUE TITLE
where is vmlinux in section 4.2

### ISSUE THREAD

**Issue by lico614257** [ppeetteerrs/gem5-RISC-V-FS-Linux#1]
4.2 Linux Kernel v5.10
Feel free to use newer versions of the kernel, but v5.10 has been tested to work.

git clone https://github.com/torvalds/linux.git $SRC/linux
cd $SRC/linux
git checkout v5.10
cp $SRC/ucanlinux/kernel.config .config
make ARCH=riscv CROSS_COMPILE=riscv64-unknown-linux-gnu- olddefconfig
make ARCH=riscv CROSS_COMPILE=riscv64-unknown-linux-gnu- all -j$(nproc)
cp vmlinux $OUT

How can get vmlinux in this section?

**Comment by ppeetteerrs** [comment]
I believe it is found inside `$SRC/linux`?
